### ISSUE TITLE
drug db

### ISSUE THREAD

**Issue by vojtechhuser** [adam-sam-brown/repoDB#1]
In this line, you load a csv file.
https://github.com/adam-sam-brown/repoDB/blob/cd4edec67e57df1d2a5f552e30a6960a38d79432/Reproduction_Scripts/drugcentral.R#L10

Could you please briefly describe how a user of your code can get this input file?

I only found .sql dump of DrugCentral
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5210665/

I wish the drugcentral schema would be documented somewhere

**Comment by adam-sam-brown** [comment]
The CSV file is now included in the FigShare repository (dx.doi.org/10.6084/m9.figshare.5634805).
